### ISSUE TITLE
Plugin doesn't work in Javis 16.1 LibreElec 7.02 due to import error

### ISSUE THREAD

**Issue by janmussel** [escoand/plugin.audio.dradio#4]
error lock says :

1```
0:52:30 T:140598592673536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name lock
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.dradio/default.py", line 30, in <module>
                                                from xbmcgui import Dialog, ListItem, lock, unlock
                                            ImportError: cannot import name lock
                                            -->End of Python script error report<--

```

Removal of wrong import line 30 : 
>> from xbmcgui import Dialog, ListItem, lock, unlock
to 
<<  from xbmcgui import Dialog, ListItem
fixes the problem...

Grüße,...
```
